### ISSUE TITLE
Consolidate ComputeGeodesicDistanceToCurve

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1003]
File: Libs/Mesh/ComputeGeodesicDistanceToCurve.cxx
After consolidation, add:

1. Python binding
2. MeshTest
3. shapeworksTest
4. PythonTest

**Comment by sheryjoe** [comment]
this tool should use libigl for geodesic computation.

**Comment by cchriste** [comment]
- on master branch we have accurate geodesic distance computations that use libigl
 - (look in Optimize/ParticleSystem/MeshDomain for these functions (MeshDomain::ComputeDistance))
 - probably move to Libs/Mesh
 - Karthik's work in mesh_geodesic_landmarks made this more efficient
 - also probably we don't need MeshWrapper since we aren't using TriMesh or MeshFIM or CGAL
 - add conversion functions as necessary (e.g., Mesh::getTrimesh)
 
We should move these distance computations to Libs/Mesh class, removing MeshWrapper.
Creating a `geodesic` branch for this.
Should also be used for #1004

**Comment by sheryjoe** [comment]
> We should move these distance computations to Libs/Mesh class, removing MeshWrapper.

We should be careful when moving these computations to the Mesh class. Some functions in the MeshWrapper were written in the context of the optimizer (eg. caching for geodesic distances). We should refactor MeshWrapper to only move or rather consolidate generic operations to the mesh class.

**Comment by akenmorris** [comment]
Should we move this to 6.3?

**Comment by archanasri** [comment]
I'm working on adding tests.
