### ISSUE TITLE
Deep_ssm and data_augmentation test issues in Windows

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1086]
The error is:
```
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:            if __name__ == '__main__':
                freeze_support()
                ...        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

Keyboard Interruption to stop the code also didn't work for me.

**Comment by cchriste** [comment]
For the main deep_ssm use case, it continuously displays this at the end(?) of each of ~6900 "generating"s. It's still running after 24 hours, so is it hung in a loop?

**Comment by cchriste** [comment]
The data_augmentation test has the same issue. Also, it uses deep_ssm directory, but might be independent (see #1081).

**Comment by iyerkrithika21** [comment]
> 
> 
> The data_augmentation test has the same issue. Also, it uses deep_ssm directory, but might be independent (see #1081).

Data augmentation and deep_ssm are related so they use the same folder.

**Comment by jadie1** [comment]
I am guessing this is because there is some parallel processing in the data augmentation process that windows doesn't like. 
Could you try changing the `processes` argument from 3 to 1 on line 75 of deep_ssm.py an running it? This will remove the parallelization. You can just try the tiny test.

**Comment by iyerkrithika21** [comment]
> 
> 
> I am guessing this is because there is some parallel processing in the data augmentation process that windows doesn't like.
> @cchriste @iyerkrithika21 Could you try changing the `processes` argument from 3 to 1 on line 75 of deep_ssm.py an running it? This will remove the parallelization. You can just try the tiny test.

This worked out.
```

Step 2. Augment data

Running point based data augmentation.
The PCA modes of particles being retained :  3
Variablity preserved: 1.0
Fitting KDE...
Generating 1/4
Generating 2/4
Generating 3/4
Generating 4/4
Done.
Wrote augmentation_splom.html



Step 3. Reformat Data for Pytorch




********************* WARNING ****************************
Pytorch is running on your CPU!
This will be very slow. If your machine has a GPU,
please reinstall Pytorch to your shapeworks conda
environment with the correct CUDA version.
**********************************************************
```

**Comment by jadie1** [comment]
Okay, I am going to make a PR with this change along with fixes for a couple other bugs I found in DeepSSM

**Comment by jadie1** [comment]
@cchriste Where is the data_augmentation test?

**Comment by cchriste** [comment]
> > The data_augmentation test has the same issue. Also, it uses deep_ssm directory, but might be independent (see #1081).
> 
> Data augmentation and deep_ssm are related so they use the same folder.

Does this mean that one depends on the other? If so, what order? If not, what is the argument to keep them using the same directory?

**Comment by akenmorris** [comment]
I get this for data augmentation with --tiny_test on windows:

![Screenshot (30)](https://user-images.githubusercontent.com/1693349/110579431-0bb2b900-8124-11eb-9b14-2187e3b6b263.png)

**Comment by cchriste** [comment]
This looks better than the inf loop we were getting. I'm downloading the latest release candidate on windows now and will try the full test.

**Comment by cchriste** [comment]
> I'm downloading the latest release candidate on windows now and will try the full test.

Windows: Downloaded, but you should delete this.
Me: click '...'
Windows: (shows list of files)
Me: click on file
Windows: You should delete this. Seriously. Your only options are 'Delete' and 'Cancel'
Me: click Cancel
Me: confused, since file is still there, but same problem, click on file again
Windows: You should delete this, seriously, your only options are DELETE and Cancel, ... 
Windows: ...and "more info" in the fine print
Me: I really don't want to delete the file I just downloaded, so I guess I'll see what more info can offer. Click "more info"
Windows: Like I said, you're way outside the safe zone here. Like, off the edge of the Flat World of Safe, but... if you _really_ wanna keep sailing this direction, fine. Fine. Click this to "keep anyway." But don't say I didn't warn you... ~Windows M. Edge (I think the M is for Marvin). 
Me: yes please, keep anyway, and finally I can open the file. *sigh* 

Is this what everyone has to do to install stuff? I presume OSX is similarly overcautious and I have just gotten used to rapidly clicking "trust anyway" a zillion times. I guess this kind of stuff maybe kind of sort of prevents the spread of viruses.

**Comment by cchriste** [comment]
> I get this for data augmentation with --tiny_test on windows:

`data_augmentation --tiny_test` output is identical. Looking at the script there is nothing but a comment when tiny_test is specified. No actual difference in what it does.

**Comment by cchriste** [comment]
`deep_ssm --tiny_test` passed. Given the rate of progress, in around 16 hours we'll know if the full deep_ssm passes as well.

@jadie1 Since parallelization is the problem, let's create an issue for this, and for bonus let the user specify how much parallelization they want to use instead of hard-coding it in the deep_ssm.py script.  Once we have that this issue can be marked resolved.

**Comment by jadie1** [comment]
> Have any of the files downloaded from girder changed contents but not names? I'd like to avoid re-downloading them if that seems safe. Thanks!

None of the femur/deep_ssm data has changed

**Comment by jadie1** [comment]
> > I get this for data augmentation with --tiny_test on windows:
> 
> `data_augmentation --tiny_test` output is identical. Looking at the script there is nothing but a comment when tiny_test is specified. No actual difference in what it does.

I am remembering now that I did not finish the data_augmentation use case (i.e. no tiny test or documentation) because we decided to replace it with the data augmentation notebook. I think we can remove this use case. It is not adding anything that deep_ssm does not do and the notebook does a much better job of explaining the process. What do you think?

**Comment by jadie1** [comment]
> `deep_ssm --tiny_test` passed. Given the rate of progress, in around 16 hours we'll know if the full deep_ssm passes as well.
> 
> @jadie1 Since parallelization is the problem, let's create an issue for this, and for bonus let the user specify how much parallelization they want to use instead of hard-coding it in the deep_ssm.py script. Once we have that this issue can be marked resolved.

Sounds good, I made issue #1136 for this.

**Comment by cchriste** [comment]
Thanks, Jadie. Closing this issue now.
