### ISSUE TITLE
femur_cut shouldn't require user interaction after a long time unzipping data

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#1102]
After download gigabytes of data, the user is asked:
```bash
Use ispotropic spacing for mesh rasterization? y/n
```

**Comment by iyerkrithika21** [comment]
This is the part of grooming; if the user enters 'y', isotropic spacing is used, or else the user can enter the spacing they require.

**Comment by akenmorris** [comment]
Additionally, can we provide recommended values for the spacing?  I answered "no" to the "ispotropic" [sic] question and it's asking me for x, y, and z spacing.  Since we are providing this dataset, perhaps we should give a suggestion.  Is 1.0/1.0/1.0 ok?

**Comment by jadie1** [comment]
Isotropic spacing is okay and should be used on this dataset. We decided to add an option for different spacing so that if a user takes this use case and adapts it for their own data they are not locked into isotropic spacing. When we redo all of the use cases I can take this interaction out since it will be clear where the spacing is defined and passed.

**Comment by iyerkrithika21** [comment]
For now, should we interchange the order of execution?
Ask about the spacing first and then proceed to the data download?

**Comment by jadie1** [comment]
> For now, should we interchange the order of execution?
> Ask about the spacing first and then proceed to the data download?
Yeah that should be fine

**Comment by cchriste** [comment]
great!
