### ISSUE TITLE
Python shapeworks env setup bug

### ISSUE THREAD

**Issue by riddhishb** [SCIInstitute/ShapeWorks#1174]
If I set the shapeworks binary path from the release zip, following code

```
shapeworks_bin_dir   = "/home/sci/riddhishb/Downloads/ShapeWorks-v6.0.0-rc8-linux/bin"
setup_shapeworks_env(shapeworks_bin_dir, verbose=False)
```

this works!

However, the binary with the source build does not work

```
shapeworks_bin_dir   = "/home/sci/riddhishb/Documents/git-repos/ShapeworksPybind/ShapeWorks/build/bin"
shapeworks_dep_dir  = '/home/sci/riddhishb/Documents/git-repos/ShapeworksPybind/ShapeWorks/dependencies/install'
setup_shapeworks_env(shapeworks_bin_dir, shapeworks_dep_dir, verbose = True)
```

this does not work

**Comment by riddhishb** [comment]
A solution as suggested by @cchriste 

First, export the python path
`export PYTHO
NPATH="/home/sci/riddhishb/Documents/git-repos/ShapeworksPybind/ShapeWorks/build/bin:$PYTHONPATH"`

it gives the library error
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libitkgdcmjpeg8-5.0.so.1: cannot open shared object file: No such file or directory
```
To fix this we need to export the library path as 

`export LD_LIBRARY_PATH="/home/sci/riddhishb/Documents/git-repos/ShapeworksPybind/ShapeWorks/dependencies/install/lib:$LD_LIBRARY_PATH"`

This fixes the issue.

**Comment by cchriste** [comment]
The desired startup script should take care of all this (#478).

**Comment by cchriste** [comment]
I also just changed setup_shapeworks_env from Testing.cpp to append instead of prepending all the potential paths for PATH, LD_LIBRARY_PATH, and PYTHONPATH (this is in the pymodule set of branches). This makes it possible for the user to change theirs and then run things like python notebooks and UseCaseTests without (much) pain. 

Was there a reason we prepended them in the first place? @akenmorris

**Comment by cchriste** [comment]
As far as the setup itself from a binary download, I'm working on it now. Do we have setup scripts for OSX and Linux? 
Another option is to build and upload a conda library so any user at any time (include us in our conda_install.sh script) can install _an explicitly-specified version_ of shapeworks. I can't remember if conda lets you install non-python executables, but that would also be kind of cool compared to downloading shapeworks at all.

**Comment by akenmorris** [comment]
> Was there a reason we prepended them in the first place?

If appending instead of prepending works, that works for me.

In general, I always prepend in scripts so that you'll always know what you'll get.  I guess I do it out of habit.

**Comment by akenmorris** [comment]
On OSX we use "pkgbuild" to create an installer.  There isn't a script that runs AFAIK.

For Linux, we don't have any sort of setup script, just a zip file.

**Comment by cchriste** [comment]
Since `install_shapeworks` adds activate scripts in conda and `devenv` ensure developers have only one binary location, this should no longer be an issue.

I have verified our executables and python module work in Linux using `devenv`.
Note that LD_LIBRARY_PATH is not set by anything, so if it's necessary for your builds we should figure out why.
Closing this issue. Please reopen or email if things aren't working.
