### ISSUE TITLE
Restructure the logic and computation of the evaluation commands 

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1192]
Right now, the ellipsoid evaluate use case calculates the generalization and specificity values for just one mode. The output is only printed on the command line. It would be useful if the use case calculated the generalization and specificity for all the modes and save the values in text files like the scree.txt.

The computation needs to be revisited.

**Comment by iyerkrithika21** [comment]
@sheryjoe, does this seem reasonable to you?

**Comment by akenmorris** [comment]
Keep in mind this may take many hours on larger size models.  Some progress output is likely needed.

**Comment by medakk** [comment]
> Keep in mind this may take many hours on larger size models.  Some progress output is likely needed.

Indeed. [tqdm](https://github.com/tqdm/tqdm) perhaps

@iyerkrithika21 I agree that this would be useful. do you know how long it takes to run it for all modes on the ellipsoid_evaluate use case? 

+a simple optimization that could be done is to just run them in parallel ie: spawn multiple processes in EvaluationUtils.py one for each mode at the same time

**Comment by iyerkrithika21** [comment]
> @iyerkrithika21 I agree that this would be useful. do you know how long it takes to run it for all modes on the ellipsoid_evaluate use case?

I will try to run it and update the time here.

Another small modification, for the scree plot, can we display the plot, save it, and then close the plot.? Right now the code freezes until the user manually closes the plot window.

**Comment by medakk** [comment]
> Another small modification, for the scree plot, can we display the plot, save it, and then close the plot.? Right now the code freezes until the user manually closes the plot window.

I preferred having it open to see the result, but that was for a single mode(similar to how it opens studio to show the reconstructions). Saving it instead sounds reasonable. Should entail changing a `plt.show()` somewhere to a `plt.savefig(...)`

+Eigen has a [BDCSVD](https://eigen.tuxfamily.org/dox/group__SVD__Module.html) implementation, which claims to be a faster, but less accurate way to compute SVD. Perhaps we can try replacing all instances of JacobiSVD in [ShapeEvaluation.cpp](https://github.com/SCIInstitute/ShapeWorks/blob/76a411824b9225b85a2c97efbdfd735a66f22439/Libs/Particles/ShapeEvaluation.cpp) with BDCSVD and see if it makes a difference

**Comment by medakk** [comment]
There are some inefficiencies in the ShapeEvaluation because it assumes we only need a single mode.

* [Generalization](https://github.com/SCIInstitute/ShapeWorks/blob/76a411824b9225b85a2c97efbdfd735a66f22439/Libs/Particles/ShapeEvaluation.cpp#L117)

```cpp
    Eigen::JacobiSVD<Eigen::MatrixXd> svd(Y, Eigen::ComputeFullU);
    const auto epsi = svd.matrixU().block(0, 0, D, nModes);
```

There is no need to recompute SVD for each different mode. We are computing it for the full matrix, and then extracting a block from that. 

* [Specificity](https://github.com/SCIInstitute/ShapeWorks/blob/76a411824b9225b85a2c97efbdfd735a66f22439/Libs/Particles/ShapeEvaluation.cpp#L117)
There seems to be a loop from 0 to nModes:

```cpp
  for (int modeNumber = 0; modeNumber < nModes; modeNumber++) {
```

So, for calculating the specificity at 5 modes, we would have already computed it for 4 modes, etc

**Comment by akenmorris** [comment]
See #697 for further discussion on the runtime.  Yes, some of them, you already have all the values for all modes if you have it for one, but not for all.

I haven't added the charts to Studio because they will be much to slow to generate.  It is easily parallelizable, but a speedup of of 8-16x isn't nearly enough except for toy models.

**Comment by medakk** [comment]
> Yes, some of them, you already have all the values for all modes if you have it for one, but not for all.

Oops yes.

**Comment by sheryjoe** [comment]
@medakk 
> There is no need to recompute SVD for each different mode. We are computing it for the full matrix, and then extracting a block from that. EDIT this is wrong

Why is that wrong? If you have the same cohort, the SVD is the same, just the modes being considered are different

**Comment by sheryjoe** [comment]
- Compactness and specificity should use the same PCA/SVD computation.
- Generalization can be redesigned to loop over leave-subject-out and use one PCA computation per leave.

**Comment by akenmorris** [comment]
Merged.
