### ISSUE TITLE
Misleading Error Messages for RunUseCase

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1308]
```
Error: cannot find shapeworks Python module. Please pass the location of the path that contains `Python/shapeworks` using the --shapeworks_source argument
```

1. The location of source ($HOME/ShapeWorks) should be passed to --shapeworks_source but the error message asks to pass the location of Python/shapeworks

2. When both --shapeworks_source and --shapeworks_path is required but if only --shapeworks_source is set then the above error is thrown. It should be updated to ask for --shapeworks_path

**Comment by cchriste** [comment]
The error messages are predominantly due to special parameters needed for developers (for whom #1313 will provide clearer instructions).

**Comment by cchriste** [comment]
#1332 will remove the need for these parameters at all since users will be able to call shapeworks executables and import python module without any parameters, even if they install in a non-standard path; #1333 will enable developers to setup their environment with a two-parameter script (the same two parameters that RunUseCase now accepts), and will work for notebooks, the command line, and for bonus it will include all of our internal python modules so no more "modify code, pip install, test code" as people have been doing.

**Comment by cchriste** [comment]
PR #1338 completely removes the arguments to specify paths and therefore the error messages. For users, conda activate takes care of all paths, and for developers, devenv ensures correct paths are used for debugging and testing of all facets, not only RunUseCase.
