### ISSUE TITLE
Feature: export xml parameter file from Studio

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1363]
Since there are parameters/features available via the command line that aren't available in Studio (e.g. cutting planes, narrow band, etc.), it would be a nice feature to be able to export an xml file of your parameters for running via command line from an existing project in Studio.

**Comment by akenmorris** [comment]
Would it be ok if we just added all of the rest of the XML params to the project spreadsheet (even if they aren't in studio)?  You can already run 'optimize' on a spreadsheet project from the command line with:

`shapeworks optimize --name project.xlsx`

The advantage of this approach is that the project will already be set up for analysis.

**Comment by patkins** [comment]
This seems like a good solution to me. Is there a list of all accepted parameters somewhere?

**Comment by akenmorris** [comment]
I've sent you a link to a google spreadsheet with all the parameters.

Now that I look at the list I realize it's going to be fairly complicated to support all of them in the spreadsheet format, mostly because I have no idea what some of them are as many are abandoned grad student project options that no one seems to know how to use.

I'm not opposed to having multiple project file formats including XML since I know it's handy to be able to edit them with a text editor on a remote machine.  The current XML format has some problems though, for example the need to interleave values for multiple domains.

**Comment by cchriste** [comment]
> Now that I look at the list I realize it's going to be fairly complicated to support all of them in the spreadsheet format, mostly because I have no idea what some of them are as many are abandoned grad student project options that no one seems to know how to use.

It will be very useful to dump unnecessary parameters, even if @archanasri and I poured ourselves into consolidating them all. Perhaps they can be described in this mysterious google spreadsheet that keeps being mentioned (any way to share this in a GitHub issue without compromising security?).

> I'm not opposed to having multiple project file formats including XML since I know it's handy to be able to edit them with a text editor on a remote machine. The current XML format has some problems though, for example the need to interleave values for multiple domains.

I want to express light opposition to xml support for command line parameters, and strong opposition to requiring parameters in a spreadsheet. Who uses spreadsheets on the command line anyway?

**Comment by akenmorris** [comment]
Not needed, shapeworks project files will be used.
