### ISSUE TITLE
Incorrect limitation to length of num_planes_per_input parameter for multiple domains

### ISSUE THREAD

**Issue by patkins** [SCIInstitute/ShapeWorks#1389]
The parameter `num_planes_per_input` seems to be restricted to a length of length(`inputs`) / `domains_per_shape` (see comment in #910), while it seems that it is expected to be the length of `inputs`.

Trial 1: My first thought was that each cutting plane was then used for the whole shape (including multiple domains, here n=2), however this resulted in the cutting planes getting applied one by one to each input (leaving the second half of the inputs without cutting planes and two different planes being applied within a shape).  
Trial 2: I then tried duplicating each cutting plane in the list, such that the number of `cutting_planes` matched the number of `inputs`. But the result was the same (although since the planes were duplicated, the same plane was applied to both domains for the first half of the shapes). 
Trial 3: I then used 2 `num_planes_per_input` and the duplicated list of planes from Trial 2, however this resulted in similar results to Trial 1

Sample data can be found in my folder here: /home/sci/atkins/SWIssues/corticalThickness/multipleDomain/

**Comment by patkins** [comment]
I think @HeavenlyBerserker was working on cutting planes, so maybe this is relevant.

**Comment by HeavenlyBerserker** [comment]
Hi @patkins , thanks for bringing this to my attention! The structure for constraints input was written before my time and I have intended to change it since I find it confusing as well. This was also implemented before "multiple domains" was working, so I appreciate any feedback to make this functionality easier to use.

The current structure stores domains in a single vector/list/array. In your case, where you have 4 inputs, 2 domains per input:
```
item 0: input_0_domain_0 aligned/dod_n02_R_femur_aligned.vtk
item 1: input_0_domain_1 aligned/dod_n02_R_femur_trabec_aligned.vtk
item 2: input_1_domain_0 aligned/dod_n09_R_femur_aligned.vtk
item 3: input_1_domain_1 aligned/dod_n09_R_femur_trabec_aligned.vtk
item 4: input_2_domain_0 aligned/dod_n10_L_femur_aligned.vtk
item 5: input_2_domain_1 aligned/dod_n10_L_femur_trabec_aligned.vtk
item 6: input_3_domain_0 aligned/dod_n11_L_femur_aligned.vtk
item 7: input_3_domain_1 aligned/dod_n11_L_femur_trabec_aligned.vtk
```
So in reality, `num_planes_per_input` should really be `num_planes_per_domain`. This was not an issue when "multiple domains" wasn't a thing, but now it just causes confusion. If you think about it, it is better to have cutting planes for each domain and not for each input since you have finer control over what gets cut. For your case, you should change the entry to the following and it should work.
```
<num_planes_per_input>
  1
  1 
  1
  1 
  1
  1 
  1
  1 
</num_planes_per_input>
```
@patkins , please let me know if you can think of a cleaner way this should work. I suggest changing the `num_planes_per_input ` parameter to `num_planes_per_domain` (changing the input verification accordingly) and add an explanation and an example to the documentation (I can write it and have Shireen can add it?). Otherwise @sheryjoe , we can think of other strategies to make this less confusing while keeping the practical aspects of being able to specify constraints for each domain.

**Comment by patkins** [comment]
As I understand the terminology based on the parameters (`domain_per_shape` and `inputs`), your list above should be:
```
input 0: shape_0_domain_0 aligned/dod_n02_R_femur_aligned.vtk
input 1: shape_0_domain_1 aligned/dod_n02_R_femur_trabec_aligned.vtk
input 2: shape_1_domain_0 aligned/dod_n09_R_femur_aligned.vtk
input 3: shape_1_domain_1 aligned/dod_n09_R_femur_trabec_aligned.vtk
input 4: shape_2_domain_0 aligned/dod_n10_L_femur_aligned.vtk
input 5: shape_2_domain_1 aligned/dod_n10_L_femur_trabec_aligned.vtk
input 6: shape_3_domain_0 aligned/dod_n11_L_femur_aligned.vtk
input 7: shape_3_domain_1 aligned/dod_n11_L_femur_trabec_aligned.vtk
```
The use of `num_planes_per_domain` to me indicates that there were would two inputs (one for each domain), not for each input, so I do not suggest changing the terminology if the logic is as you describe. (I would however make sure that the parameter name for the spheres matches that of the planes.) 

I apologize if I didn't make it clear in my issue, but shapeworks errors out if a value is provided for each input under `num_planes_per_input` as you proposed (see comment in #910); only an input for each shape (using the terminology above) is allowed (i.e. 4 values as listed above).

**Comment by HeavenlyBerserker** [comment]
Ah, I see. I'll look into this issue then.
