### ISSUE TITLE
`get-field` command line for Mesh should also be able to print array of values (in addition to being stored in sharedData.field)

### ISSUE THREAD

**Issue by archanasri** [SCIInstitute/ShapeWorks#1420]
sharedData.field/array should return array of values. We shouldn't be accessing field values one by one.

Related to #935

**Comment by cchriste** [comment]
More specifically, we have added functions to retrieve fields from a mesh, but those are brought into the behind-the-scenes sharedData struct (the same as when an image or a mesh is loaded). We probably want a command to simply dump these to the console so the user can get all the values at once rather than force them to use the commands that only return a single value. 

However, like many other issues with the command line, this functionality is limited, in this case (as with get-field-value) the accuracy of data is lost. e it might still be handy for debugging, actual pipelines should never be implemented using the command line.

**Comment by cchriste** [comment]
More specifically, add an option to `get-field` in MeshCommands to dump the field to the command line.

**Comment by HeavenlyBerserker** [comment]
@akenmorris Is this still needed?
