### ISSUE TITLE
Python: add global ICP-based alignment for multiple domains (segmentations and mesh grooming)

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1444]
Split from #1403

**Comment by iyerkrithika21** [comment]
@sheryjoe @akenmorris 
The reason the reference shape appeared small was that it was being antialiased twice. 
This was due to pass by reference assignment with :
`reference_seg = shape_segs[ref_index]`
This is the case with all the use cases, and the  assignment should be changed as follows:
`reference_seg = shape_segs[ref_index].copy()`

When the mode of variation is rotation, applying ICP on segmentation aligns all the ellipsoids with the same rotation as the reference. The operation is as intended and can be verified by looking at the grooming pipeline of the `ellipsoid` use case. But we want to preserve the rotation as a mode of variation for the multiple domain use case. 

In Studio, the local particles are multiplied with the transformation matrix, and the results are correct. Hence for the python use cases, can we push the alignment step for the next release when we resolve #1386 as we incorporate the passing of the transformation matrices to the optimizer in python?

![image](https://user-images.githubusercontent.com/11266258/132600354-731da5d5-4052-40f1-bbf3-630f778b2d3a.png)
```
import shapeworks as sw
>>> im1 = sw.Image("ellipsoid_03.nrrd")
>>> im1.write("im1.nrrd",compressed=False)
>>> im2 = im1
>>> im2.antialias(100)
>>> im2.write("im2_antialias.nrrd",compressed=False)
>>> im1.antialias(100)
>>> im1.write("im1_antialias.nrrd",compressed=False)
```

**Comment by sheryjoe** [comment]
@iyerkrithika21 
>When the mode of variation is rotation, applying ICP on segmentation aligns all the ellipsoids with the same rotation as the reference. 

This should only happen if you do the domain-specific alignment.

> But we want to preserve the rotation as a mode of variation for the multiple domain use case.

Should that be preserved with global alignment?

**Comment by iyerkrithika21** [comment]
Followed the same steps as per Groom.cpp for global alignment from : https://github.com/SCIInstitute/ShapeWorks/blob/3b936bb407ad478171a343cf0e4c90f3a8678782/Libs/Groom/Groom.cpp#L484

Input: only ellipsoid 2 rotates
![image](https://user-images.githubusercontent.com/11266258/132735552-3838e97c-dfd8-4e75-9e7e-173a0f386c45.png)

Output: after alignment both the ellipsoids are rotating. 
![image](https://user-images.githubusercontent.com/11266258/132735357-c314f66f-a353-4f21-9fe2-33bf6b7b1e1a.png)


You can check my code here: https://github.com/SCIInstitute/ShapeWorks/blob/dbbb4c45dc1538237982f6db91ccdae8273089fd/Examples/Python/ellipsoid_multiple_domain.py#L149

**Comment by iyerkrithika21** [comment]
As per discussion with @sheryjoe : Global alignment will be added for left atrium with appendage dataset in the next release

**Comment by iyerkrithika21** [comment]
Use case added #1961
