### ISSUE TITLE
Update doc for project API

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#1720]
This includes adding documentation for project spreadsheets and updating doc for all use cases that run optimization.

**Comment by akenmorris** [comment]
See what we have now for the old XML format:

http://sciinstitute.github.io/ShapeWorks/6.3/workflow/optimize.html

**Comment by iyerkrithika21** [comment]
Plan for the documentation: 

1. Include a page with details about the project sheet. Describe all the sheets and columns 
2. Show an example of generating the project sheet using python
3. Reference this page instead of the XML file part we do right now
4. For each use case, show ungroomed data and explain the grooming pipeline and how the transforms are passed to the optimizer. 
5. We could show how the data would look if the transform were applied.
