### ISSUE TITLE
Procrustes does not work when run in a Mutli-domain model

### ISSUE THREAD

**Issue by kasknutson** [SCIInstitute/ShapeWorks#1755]
I ran the latest version of Shapeworks (6.2.1) and Procrustes caused all the bones to share the same space, rather than maintaining the joint relationships. (as seen in the image attached). This is a 6 bone model with 47 subjects.  
![image](https://user-images.githubusercontent.com/85652425/166330109-356a8d0c-1709-4640-a9cb-d450638f07b3.png)

**Comment by akenmorris** [comment]
Were these shapes aligned in Studio, or how was the project set up?  It's working for me with 6.2.1.

**Comment by rl00100** [comment]
I had the same issue when i edited the multi_domain example to work with my data.  I think the issue comes from the set up of the project file. Either the global alignment transformation matrix needs to be added to the alignment columns of each sub-domain. Alternatively, the transform can be applied to the raw image, then these columns need to be filled with an transformation matrix with no translation, rotation, or shear. 

That fixed the issue for me, hope this helps.

**Comment by iyerkrithika21** [comment]
> I had the same issue when i edited the multi_domain example to work with my data. I think the issue comes from the set up of the project file. Either the global alignment transformation matrix needs to be added to the alignment columns of each sub-domain. 

The multiple domain use cases perform local alignment because the mode of variation is rotation in the second ellipsoid.  We have not implemented global alignment in the examples yet. 
The excel sheet does support global alignment.

**Comment by akenmorris** [comment]
Fixed in #1937
