### ISSUE TITLE
Release Notes 6.3

### ISSUE THREAD

**Issue by iyerkrithika21** [SCIInstitute/ShapeWorks#1759]
Please add to this issue a paragraph (plus videos/snapshots for illustration) about each new/improved/bug-fix included in this release.

**Comment by jadie1** [comment]
Did we mean to close this?

Here are some release notes:

Use Cases Refactoring
- Added grooming steps to mesh-based use cases using the mesh Python API
- Alignment transformations are now passed to the optimizer and used in optimization instead of being applied before optimization. This results in local particles in the original data's coordinate system, allowing for easier subsequent analysis.
- The use cases now use project spreadsheets in optimizations instead of XML files. This format is more interpretable and allows of better integration with Studio.
![image](https://user-images.githubusercontent.com/54382613/168448217-080a9320-a6da-47dd-ab94-7ef27cfd847b.png)
- The femur use case has been refactored into a single use case where alignment transforms and cutting plane constraints are passed in optimization. 
![image](https://user-images.githubusercontent.com/54382613/168448321-86a46865-b9e0-4b74-aa98-b7359506a418.png)
- All use case documentation has been updated to be clearer and reflect these changes.

DeepSSM Use Case
- The DeepSSM use case has been updated to demonstrate the full pipeline, including training data generation instead of relying on the femur use case to create a training shape model.
- The use case now demonstrates how to optimize validation particles via fixed domain optimization where the training particles are unchanged.
- Image-to-image registration tools have been added to prepare DeepSSM input images without requiring corresponding segmentations or meshes. This allows for true inference with DeepSSM.
![image](https://user-images.githubusercontent.com/54382613/168448249-37ea2f6c-60cb-4983-928b-d0691698c73a.png)
- Automatic verification has been added for the DeepSSM tiny-test.
- Detailed documentation has been added to explain each step of the full DeepSSM pipeline. 
![image](https://user-images.githubusercontent.com/54382613/168448257-4da056b0-60d4-4366-b3c5-3b24de42ebc1.png)

Incremental Use Case
- A new use case has been added, demonstrating how a shape model can be optimized incrementally on 3D supershapes. This approach is beneficial when the cohort of shapes is very large, and single optimization would be slow, and when the dataset is small but contains a large amount of shape variation. 
- Functionality has been added to select the order of shape optimization based on the distance of each shape to all others in the cohort. This allows for particles to be fit to inlier shapes first, then outliers. 
- Documentation has been added that explains the use case and quantitatively demonstrates the benefit of incremental optimization.
![image](https://user-images.githubusercontent.com/54382613/168448279-5b553e38-8db6-4d34-9894-711f1575b6a1.png)

**Comment by HeavenlyBerserker** [comment]
**Constraints**
- Added constraints functionality **for the mesh domain both clipping and augmented lagrangian** together with a flag to flip between the two options.
- Added **documentation for using constraints in Studio**.
- Added a **Studio use case for constraints** and a **pseudo-tutorial for it** in the documentation.

**Comment by iyerkrithika21** [comment]
Femur: Group Difference Statistics in Python was updated to perform LDA
- The use case also demonstrates Linear Discrimination of Variation (LDA) for analyzing shape variation between the subgroups.
![image](https://user-images.githubusercontent.com/11266258/168459008-5a2f05c9-f270-44c8-87f6-80ecc4282c20.png)

**Comment by akenmorris** [comment]
* Color maps
* Difference to mean
* Super impose and surface distance
* Apply groom to all domains
* Montage export 
* Image export
* Fringe plots
* Export scalar values 
* Image slice sync
* Landmarks, landmark registration, landmark seeds
* Cutting planes
* Free form constraints 
* Procrustes scaling only mode
* Image support (shown slices)
* Good/bad particle display
* LDA chart in Studio

**Comment by akenmorris** [comment]
Complete in #1777
