### ISSUE TITLE
Find FFC video and add to Studio online docs

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#1863]

**Comment by HeavenlyBerserker** [comment]
I have a bunch demo videos, but I think I decided not to upload them and just work with images because I was worried that they'd be too heavy. 

Here are the videos for each step
[constraints_vids.zip](https://github.com/SCIInstitute/ShapeWorks/files/9592143/constraints_vids.zip)

Here's a full demo video

https://user-images.githubusercontent.com/11202328/190867122-89a96ba6-f29e-483d-9d6a-a4fa6238f1f6.mp4
