### ISSUE TITLE
Fringe plots for PCA Modes Visualization

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#254]
Hi All,

I have a feature request for visualizing modes of variations.  Currently I use a distance map tool to create fringe plots in PostView (https://febio.org/postview/).  This creates a distance comparison between +/- 2 SD from the mean shape to highlight anatomical features.  See below an example of visualizing 3 modes of variation resulting from a ShapeWorks model of the talus (one ankle bone).  To do this I compare the mean shape to the +2SD surface and additionally compare the mean shape to the -2SD surface.  In the situation of presenting findings in manuscripts or posters, it provides a nice visual with color distinction of where differences reside.  Do you think this is something that could be easily included in View2 or the new ShapeWorksStudio analysis tab?

Thanks!
Amy

****************************************************
Amy L. Lenz, PhD
Postdoctoral Research Associate
Orthopaedic Research Laboratory
University of Utah Orthopaedics
590 Wakara Way, RM A118

****************************************************
![fringeplot](https://user-images.githubusercontent.com/3253036/68441012-fd4c3a00-0189-11ea-8a1b-71bbf1629828.png)

**Comment by akenmorris** [comment]
Looks cool.  We have some functionality in View2 do create these color plots to shot differences between groups.  It is feasible to extend this to PCA shapes as well.  This would be in Studio of course.

**Comment by sheryjoe** [comment]
@akenmorris this will be also needed for Andy's project.

**Comment by patkins** [comment]
This also recently came up in discussions within our group, it would be great to see this in Studio!

**Comment by sheryjoe** [comment]
@akenmorris is this feasible for 6.3?

**Comment by patkins** [comment]
A couple of additional examples of visualizing group differences (note the use of diverging color schemes instead of jet and a discrete instead of smooth color map). It can also be helpful to allow the user to define the specific bounds of the colormap. Hope this helps.
This is a simple single figure showing group differences:
![image](https://user-images.githubusercontent.com/13870137/165167829-9e9f8463-1e5c-4830-8536-ba1e73d837cc.png)
Similarly, a part of a figure showing (essentially) group differences:
![Example1](https://user-images.githubusercontent.com/13870137/165167892-d6ee0c3b-d0e7-42f1-b2a0-19795d89d0d1.png)

**Comment by akenmorris** [comment]
Lots of options now:

* #1764

**Comment by akenmorris** [comment]
Completed.
