### ISSUE TITLE
Studio visualization artifact with procrustes

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#279]
When procrustes is on for optimization, the visualization of the samples are rendering incorrectly in studio analyze. Shireen suspects this is because the scaling has changed the coordinates. 
The same samples render correctly in View2, here are some examples:

![Studio_Sample0](https://user-images.githubusercontent.com/54382613/71024247-b70bc400-20c1-11ea-8fd7-9d5f6798409f.png)
![View2_Sample0](https://user-images.githubusercontent.com/54382613/71024248-b70bc400-20c1-11ea-9b8d-9b4bfa22ce32.png)
![Studio_Sample1](https://user-images.githubusercontent.com/54382613/71024249-b70bc400-20c1-11ea-9e82-8b857b3171db.png)
![Vew2_Sample1](https://user-images.githubusercontent.com/54382613/71024250-b70bc400-20c1-11ea-8351-9dc06a0d1be9.png)

**Comment by akenmorris** [comment]
Must turn "center" off.

I'm not sure why it's applying to one and not the other.  The center checkbox is really only there for the "original" images, so that you can see them all without having to center them all via grooming first (because they share a camera).

Perhaps "center" should hide when on groomed/reconstructed.
