### ISSUE TITLE
ParticleSystem and Optimize classes should be in shapeworks namespace

### ISSUE THREAD

**Issue by cchriste** [SCIInstitute/ShapeWorks#431]
, etc.

**Comment by sheryjoe** [comment]
@akenmorris @medakk has this been resolved?

**Comment by medakk** [comment]
No, everything is still in the itk namespace.

**Comment by akenmorris** [comment]
As we un-ITK these classes we will move them out.  For example, the Optimize and Sampler classes are not longer ITK objects and now live in the `shapworks` namespace.

For many of these classes, `ParticleGradientDescentPositionOptimizer` for example, it doesn't make chance to change the namespace without making them non-ITK classes.  Otherwise you will have to add the `itk` namespace to many of the types used.

**Comment by akenmorris** [comment]
Done.
