### ISSUE TITLE
Add command to get distance between meshes

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#527]
We need a new ShapeWorks command to quantify the surface-to-surface distance between two meshes. This will be used for clustering to select a representative subsample or to select the reference sample from meshes.

**Comment by sheryjoe** [comment]
[HausdorffDistance2.zip](https://github.com/SCIInstitute/ShapeWorks/files/4742473/HausdorffDistance2.zip)
@jadie1 The attached code is a standalone tool that computes surface-to-surface distances. Please refer to the readme and latex/document.pdf 

This code is based on a 2011 VTK journal (in the latex folder), however, their class (vtkHausdorffDistancePointSetFilter) that computes surface distances is already incorporated (and probably updated) in VTK. Let's use this VTK class and put together a shapeworks command that performs similar computation.

https://vtk.org/doc/nightly/html/classvtkHausdorffDistancePointSetFilter.html

Given mesh A and mesh B, this code can report vertex-to-vertex and vertex-to-triangle distances (-t argument). It also reports A-to-B and B-to-A as a vertex-wise distance field on mesh B and mesh A, respectively. 

For users and/or use cases that would need summarize/aggregate values (e.g. min, max, mean, std ... etc). I would add an independent command that would take in a mesh (vtk) with scalars and compute these aggregate values (based on input args), rather than interweave this into the distance tool.

**Comment by jadie1** [comment]
Notes on building HausdorffDistance2.zip:

In CMakeLists.txt change this:
   TARGET_LINK_LIBRARIES( HausdorffDistance2 vtkIO vtkCommon )
to:
    TARGET_LINK_LIBRARIES( HausdorffDistance2 ${VTK_LIBRARIES} )

 When calling  CCMAKE, use -DCMAKE_PREFIX_PATH=/path/to/dependencies/install
