### ISSUE TITLE
RunUseCase help does not show defaults for input args

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#593]

**Comment by jadie1** [comment]
Most of the input args are flag, they are on if included or off if not. Should we specify the default is off? 

The only args which require values are use_case, use_subsample, and  shapeworks_path.

- use_case does not currently have a default value. It prints the help if RunUseCase is called without a use case. Should we set a default value? I think that could lead to confusion.
- use_subsample also does not have a default currently. We could set a default value for when a user adds the tag but doesn't specify the number, but what should that be?
- shapeworks_path has a default value which is already specified in the help

![image](https://user-images.githubusercontent.com/54382613/91647338-f6433080-ea16-11ea-8704-0c3c02838fdf.png)

**Comment by sheryjoe** [comment]
- Agreed on the use_case. It will be confusing to have a default.
- We could use 3 samples as a default for use_subsample if the user didn't specify the number but print a warning that this number was not given and this default will be used (probably with a "Press any key to continue ... " message to confirm that this is what the user wants).

**Comment by cchriste** [comment]
- flags are only enabled if set. It's implicit they aren't used if they're not set. Not sure how much more clearly we could/should be about this... _leave as is_
- agreed: no default use case should be provided
- use_subsample, start_with_prepped_data, start_with_image_and_segmentation_data, and use_single_scale are all specific to subsets of use cases. I don't currently have a suggestion on how to clarify this to users, but it _is_ confusing and should be addressed
  - regarding use_subsample, it would be better for the help tio suggest a default value since it's not a flag, but a manual specification of... the number of samples to use? It's not even clear looking at the code what this is doing. Here's the code:

**Comment by jadie1** [comment]
I added the default arg for use_subsample to pull request #656
