### ISSUE TITLE
Docs: Update AutoDoc for MkDocs

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#650]
[] which dir to use for autodoc for commands? see dev/autodoc
[] change github action for autodoc dir for commands
[] update docuilts to generate md for mkdocs (ShapeworksCommand.md)

**Comment by cchriste** [comment]
I'm not sure where to include this, and I don't want to hold up existing pull requests, so I'm adding it here:

Let's clean up the two autodoc pages in our documentation, `How to Auto-generate documentation`, and `Getting Started with mkDocs`, to be more clear for a developer/user. Since conda_installs already includes mkdocs, we can include that portion, but not first. Instead... 
- _first_ we should include `mkdocs serve`, 
- then describe the locations of the .md documentation files

This enables the developer to see what they're doing in realtime. Even `DocumentationUtils.generateShapeWorksCommandDocumentation` will update the associated .md files shown by `mkdocs serve` when it is executed.

I suggest combining the two pages and putting `Deploying on GitHub pages` very last, adding some "Important" section to this to warn the user that when they do this, it's updating documentation seen by _everyone_, and recommend it be associated with the version of SW currently in master branch.

**Comment by sheryjoe** [comment]
This issue has been resolved.
