### ISSUE TITLE
Mesh Bounding Box

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#672]
We need a way to infer a reasonable origin and size for rasterization based on a group of meshes. Th current function to do so is: ComputeRasterizationVolumeOriginAndSize

This function requires VTK meshes. When I try to convert the attached PLY meshes to VTK using ply2vtk (also attached) then call  ComputeRasterizationVolumeOriginAndSize with the attached XML it gives a VTK error saying the meshes can not be read.

We want to fix this function so that it:
- Has consistent naming, maybe something like mesh bounding box
- Can take a mesh in any format
- Correctly reads VTK meshes

[TestMeshes.zip](https://github.com/SCIInstitute/ShapeWorks/files/5138846/TestMeshes.zip)

**Comment by jadie1** [comment]
@akenmorris  helped me find that the issue was actually just in my xml. ComputeRasterizationVolumeOriginAndSize works as expected. @cchriste should we keep this issue because this method could stand to be refactored? Or should we remove it for now and handle that later?

**Comment by cchriste** [comment]
I suggest we keep the issue since it will help us to specifically identify each subcommand to be created, and this is one of them. It's useful since part of the work to understand what this command has been identified here. If you can add the specific changes required for it to work correctly you will have saved effort required to consolidate the command since we'll have to do it anyway. You can leave it assigned to Archana and I.

**Comment by jadie1** [comment]
Okay, I attached a new zip which has the corrected xml. 
[Corrected_TestMeshes.zip](https://github.com/SCIInstitute/ShapeWorks/files/5139165/Corrected_TestMeshes.zip)

**Comment by archanasri** [comment]
I tested the consolidated ComputeRasterizationVolumeOriginAndSize command with the data from Corrected_TestMeshes.zip and it was successful.
