### ISSUE TITLE
fixed_domains tag is missing in ellipsoid_fd data

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#736]
The correspondence xml file in the shape_models folder in the portal does not contain the fixed_domains tag. How is this run in a fixed domains mode?

**Comment by akenmorris** [comment]
I think the fixed domains example is a little complicated since it uses an existing shape model to start with.  The "shape_model" in ellipsoid_fd-v0/shape_models is the starting point for the use case and includes shapes up to 19.  When you run it, adds two new shapes, 20 and 21, and sets the previous model as the fixed domains.

Do you want the ellipsoid_fd-v0/shape_models to contain the shape model before or after, or both?  Right now, it's the base model (before).

**Comment by sheryjoe** [comment]
We should add  both the pretrained shape_model (before) and the shape model with new samples.

**Comment by sheryjoe** [comment]
shape_model: output of fixed domain use case similar to other use cases (xml should have the <fixed_domains>)
pretrained_shape_model: this use case needs to run.

**Comment by sheryjoe** [comment]
@jadie1 where are we on this?

**Comment by jadie1** [comment]
I have fixed it on the portal.
