### ISSUE TITLE
use-case-data-v2 missing data

### ISSUE THREAD

**Issue by jadie1** [SCIInstitute/ShapeWorks#738]
@0leks it appears that when you made the use-case-data-v2, some data went missing that was in use-case-data-v1. There is also data not in use-case-data-v1 or use-case-data-v2 that I think should be there. Here are the issues:

-  **use-case-data-v2/femur-v0** was missing most of the shape models - I have already fixed this.
-  **use-case-data-v2/left_atrium-v0** is missing most of the shape models - @AtefehKashani I can copy these from use-case-data-v2/left_atrium if they have not changed, I know you improved the shape model recently so I wanted to check.
- **use-case-data-v2/ellipsoid-v0** has 30 segs, 22 meshes, 15 groomed/distance_transforms, and 15 shape_models - Why aren't these numbers all the same and are the shape models for ellipse or ellipse_mesh?
- **use-case-data-v2/ellipsoid_fd-v0** - @riddhishb I don't see shape models for the 2 new distance transforms (also see issue #736)
- @medakk use-case-data-v2/femur-v0/goomed/meshes/ are from the femur mesh use case right? There is one missing.
- @sheryjoe @akenmorris Should the mesh use cases (ellipsoid_mesh, femur_mesh, and lumps) have shape models on the data portal? Currently none of them do.

**Comment by medakk** [comment]
Looks like `n07_L_femur.ply` is missing in femur/groomed/meshes
@0leks  was this intentional or should I add it back?

**Comment by 0leks** [comment]
I believe I removed `n07_L_femur` because it was messing up the grooming steps. It kept getting stretched out during alignment

**Comment by sheryjoe** [comment]
The target is to have all datasets have an optimized shape model and their correspondence/analyze xml files so that users can just download the data and see the expected shape model without having to run the full pipeline. If a dataset is used in different use cases, e.g. with and without cutting planes, a shape model for each use case would be released.

I think we should consider automating this. For instance, we could have a script that would use the output of RunUseCase to upload the generated shape model and groomed data used for correspondence to the portal, this entails keeping track for versioning. @0leks @akenmorris thoughts?

**Comment by AtefehKashani** [comment]
@jadie1 what do you mean by the most of data? I have checked and we have the output of shape model particles for single/multi scale and also, the input data. If you mean the groom output, yes it is missing, because at that time we didn't want to have the up. I will upload the grooming output to the version_0.

**Comment by jadie1** [comment]
@AtefehKashani Sorry I forgot to update this but I fixed the shape models yesterday, there were only 50 files but I copied them over so all 175 are there now.  I don't think anything more needs to be done for the LA data this release.

**Comment by jadie1** [comment]
Remaining issues:
- use-case-data-v2/ellipsoid-v0 has 30 segs, 22 meshes, 15 groomed/distance_transforms, and 15 shape_models - Why aren't these numbers all the same? Do we leave this for now since we will be updating the ellipse data next release?
- No shape_models for ellipsoid_fd, ellipsoid_mesh, femur_mesh, lumps.

**Comment by sheryjoe** [comment]
see dev/datasets.md 
shape_models/<data>_mesh/*particles (local + world)
shapes_models/<data> (for distance transforms)
      
for each:
shapes_models/<model_name>_correspondence.xml
shapes_models/<model_name>_analyze.xml (point files, world, local, distance transforms)

Related issues for next release:
- automating uploading released output to data portal

**Comment by sheryjoe** [comment]
@jadie1 where are we on this?

**Comment by jadie1** [comment]
It is all accounted for, closing the issue now.
