### ISSUE TITLE
Studio: remove world_points_files and use point_files in analyze

### ISSUE THREAD

**Issue by sheryjoe** [SCIInstitute/ShapeWorks#744]
Why do we have the <world_point_files> tag if it is always the same as <point_files>? If we remove world_point_files, this still will provide backward compatibility with old parameter files and will reduce redundancy.

**Comment by akenmorris** [comment]
The reason for the duplicated tag is so that the same parameter file is compatible with other executables such as ReconstructMeanSurface.

**Comment by sheryjoe** [comment]
What if we use <world_...> and <loca_...> in both studio and other executables? could we get rid of the point_files? or allow to only give <world_...> and <loca_...> and internally use world_ for point_files?

**Comment by akenmorris** [comment]
Yeah, I agree that should be good going forward.  But, I usually try to keep the new files compatible with the old tools (if it's simple) so that users/developers can easily compare.  We had the same discussion about changing the different optimize parameters from a number to a string.

I'm fine with the decision, but we should just be cognizant that we're making the decision to break the format for older tools.

**Comment by sheryjoe** [comment]
> Yeah, I agree that should be good going forward. But, I usually try to keep the new files compatible with the old tools (if it's simple) so that users/developers can easily compare. We had the same discussion about changing the different optimize parameters from a number to a string.
> 
> I'm fine with the decision, but we should just be cognizant that we're making the decision to break the format for older tools.

I totally agree on provide backward compatibility. I propose to make Studio not having to take in both point files and world point files. We can add in the documentation that this redundancy for backward compatibility.

**Comment by akenmorris** [comment]
@sheryjoe Can we close this issue?  I don't think anything needs to change in Studio.  Studio already does not require the <point_files> tag.  It has always been optional.  The behavior in reading old View2/XML files is:

if <point_files> is specified, these are set for the local and world.

if <local_point_files> is specified, these are used for local points instead of the above.

if <world_point_files> is specified, these are used for world points instead of the above.

With this behavior, we can read old files that only specify <point_files>.

Perhaps the python use cases should be changed to not write <point_files>?  Thought this will make them incompatible with View2 (which is deprecated anyway).

**Comment by sheryjoe** [comment]
I think we can close this given the behavior of reading old files. Moving to a spreadsheet project file will also make this issue irrelevant. I don't think use cases need to change at this point.
