### ISSUE TITLE
Mesh::bounds() returns invalid pointer

### ISSUE THREAD

**Issue by medakk** [SCIInstitute/ShapeWorks#877]
In [Mesh.h](https://github.com/SCIInstitute/ShapeWorks/blob/5c3421c58df4512e5030fc15e3dfc53fe92fedf8/Libs/Mesh/Mesh.h#L51):

```c++
  /// get bounds
  double* bounds() const {
    double bb[6];
    mesh->GetBounds(bb);
    return bb;
  }
```

that function returns a pointer `bb` which would be invalid once the function returns

**Comment by archanasri** [comment]
This has been fixed in the mesh_party branch. Changes will be pushed to the master branch soon.

**Comment by akenmorris** [comment]
Since the mesh_party branch is not planned to be merged soon, we should re-open this issue. We will probably need a separate fix for this for the next release. 

In general, I would suggest that we close issues only when they have been merged to the master branch. This will ensure that a bug/feature that has been marked fixed/closed can be immediately used by a user by downloading the development binary deployment.

**Comment by cchriste** [comment]
I agree with Alan that issues should not be closed until fixes are merged with master.

**Comment by sheryjoe** [comment]
Agreed on closing issues when fixes merged to master.

**Comment by akenmorris** [comment]
Now merged.
