### ISSUE TITLE
Studio: Save particles to a directory prefixed with the project name

### ISSUE THREAD

**Issue by akenmorris** [SCIInstitute/ShapeWorks#909]
This would allow a user to make multiple copies of a project with different optimization settings and not have them clobber each other's particle files.

**Comment by akenmorris** [comment]
Hey @medakk, what do you think if we added two pref options:

groom prefix -> relative folder to place groomed files, default = "groomed"
particle prefix -> relative folder to place particle files, default ="<project>_particles"

Where <project> gets replaced by the project name.

**Comment by medakk** [comment]
> Where gets replaced by the project name.

The underscore gets replaced?

Yeah, that sounds like good option. Default to overwrite grooming + NOT overwrite particles when saving a new file.

**Comment by akenmorris** [comment]
Haha, markdown got my greater than and less than

**Comment by akenmorris** [comment]
So one issue is that you don’t have to save the project before running optimize. What should we do in this case?  “New_Project_particles”?  Or just “particles”?

We could force the user to save first, but I don’t really like that option.

**Comment by medakk** [comment]
What I'm seeing with current Studio is that it doesn't save any particles files(are they only in memory?) until I "Save" the entire project.  So there will always be a filename by the time we save the particles. (caveat is checkpointing, but Studio doesn't support that right now)

But for the "groomed" folder, we don't know _where_ the project xlsx is going to be saved...

**Comment by akenmorris** [comment]
Yeah, that’s right. Grooming was doing the same, but this was a scalability limitation, so they are always saved to disk. 

The default now is that they are written in the same folder as the input files, it doesn’t matter where you save the xlsx file. We can keep that convention. But if we support project named groom folders, then we won’t always know the project name yet.

**Comment by medakk** [comment]
Hmm. One solution I can see is to save everything to /tmp/ until a project filename is known. Then move those folders. But it'd be very messy to implement (slow move operation if /tmp/ is on a different filesystem, disk bloats up if we crash etc)

Maybe we start with:
* particles by default are stored in <project_name>_particles/ . This is not a problem because we save the particles only if the project is saved
* groom by default is stored with the input meshes
* expose an option for the user to change either of these locations
